version: "3.8"

services:
  api:
    build: cinelingo-api
    ports:
      - "3005:3005"
    links:
      - db
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://db:5432
  db:
    image: postgres:latest
    container_name: my_postgres_lang_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinelingo2
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  web:
    build: cinelingo-ui
    ports:
      - "4001:4001"
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://db:27017
    

volumes:
  pg_data:
    driver: local
